name: JestTest

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo test
        run: echo "hoge fuga"
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: test
        run: npm test